<?php

namespace Rodrigo\IcarusBundle\Entity;

/**
 * ResponsavelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsavelRepository extends \Doctrine\ORM\EntityRepository
{
}
